### ISSUE TITLE
Credential must not commit into the project

### ISSUE THREAD

**Issue by worrawutp** [zx4545zx/Heroes#2]
Here are the information that we must not hard code and commit it to the repository.
* Any kind of credentials, secret or token
* Any password, passcode
* Any personal information that can identify to person such as id card, phone number
* Any confidential info like credit card

Use the `.env.local` or other environment files to store those information describe above.

_note:_ We should refer the environment variable name from `.env.local` file but we must not commit it to the repository as well. This env file usually pass around to the development team by other way consider private and secure.

**Comment by zx4545zx** [comment]
#4 able use authorization without hardcode and rename .env to .env.local
